(()=>{'use strict';
const KEY='little-world-v2';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const arr=v=>Array.isArray(v)?v:[];
const obj=v=>v&&typeof v==='object'&&!Array.isArray(v)?v:{};
const today=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const yesterday=()=>{const d=new Date();d.setDate(d.getDate()-1);return today(d)};
const hash=s=>{let h=2166136261;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0};
const pick=(a,seed='')=>a.length?a[hash(seed)%a.length]:null;
const legacyMemories=()=>{try{const v=JSON.parse(localStorage.getItem('littleWorldMemories')||'[]');return Array.isArray(v)?v:[]}catch{return[]}};
function migrate(){let v;try{v=JSON.parse(localStorage.getItem(KEY)||'null')}catch{}if(v&&v.version===2)return sanitize(v);const oldHearts=clamp(Math.floor(num(localStorage.getItem('littleWorldHearts'),0)),0,1000000);const oldLast=localStorage.getItem('littleWorldLastVisit')||'';const oldCur=Math.max(0,Math.floor(num(localStorage.getItem('littleWorldCurrentStreak'),0)));const oldBest=Math.max(oldCur,Math.floor(num(localStorage.getItem('littleWorldBestStreak'),0)));return sanitize({version:2,hearts:oldHearts,memories:legacyMemories().map((m,i)=>({id:`legacy-${i}-${hash(m?.text||i)}`,icon:String(m?.icon||'♡'),text:String(m?.text||'Memory'),source:'legacy',at:Date.now()-i,date:null})),daily:{last:oldLast,current:oldCur,best:oldBest},completed:{},mori:{lastRewardDate:'',rewardCount:0},recentRandom:[],page:'home',levelQueue:[]})}
function sanitize(v){v=obj(v);return{version:2,hearts:clamp(Math.floor(num(v.hearts)),0,1000000),memories:arr(v.memories).filter(m=>m&&typeof m==='object').slice(-500).map((m,i)=>({id:String(m.id||`m-${i}`),icon:String(m.icon||'♡').slice(0,16),text:String(m.text||'Memory').slice(0,500),source:String(m.source||'unknown').slice(0,50),at:Math.max(0,num(m.at,Date.now())),date:m.date?String(m.date):null})),daily:{last:String(v.daily?.last||''),current:Math.max(0,Math.floor(num(v.daily?.current))),best:Math.max(0,Math.floor(num(v.daily?.best)))},completed:obj(v.completed),mori:{lastRewardDate:String(v.mori?.lastRewardDate||''),rewardCount:Math.max(0,Math.floor(num(v.mori?.rewardCount)))},recentRandom:arr(v.recentRandom).map(String).slice(-3),page:['home','memories','mori','album','settings'].includes(v.page)?v.page:'home',levelQueue:arr(v.levelQueue).map(n=>Math.floor(num(n))).filter(n=>n>0&&n<6)}}
let state=migrate();
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));return true}catch(e){console.warn('Our Little World save failed',e);return false}}
const levels=[
{min:0,name:'Just Us ♡',icon:'🤍',description:'Our little world is only getting started.',up:'Okay, this is officially becoming a thing.'},
{min:25,name:'Attached',icon:'💗',description:"You're becoming suspiciously difficult to stay away from.",up:'Apparently I got attached. Shocking.'},
{min:50,name:'Inseparable',icon:'🫶',description:'At this point, wherever you are is probably where I am too.',up:"Yeah. We're kind of a package deal now."},
{min:100,name:'My Favorite Person',icon:'💞',description:"Mori can complain all he wants. You're still my favorite.",up:"You're my favorite person. Don't make this weird."},
{min:200,name:'Disgustingly In Love',icon:'💘',description:"We're officially the couple everybody else has to tolerate.",up:'This is getting embarrassing. I adore you.'},
{min:400,name:'Endgame ♡',icon:'💍',description:'No next level. Just us, indefinitely.',up:"Looks like you reached the end. You're stuck with me now."}
];
const dailyEvents=[
{id:'sleepy',times:['morning'],icon:'☀️',title:'Morning, Sleepy',text:'Elias looks at you for a second. “You look like you need five more minutes.”',reward:3,memory:'Elias tried to convince you to stay in bed five more minutes.'},
{id:'there',times:['day','evening'],icon:'💗',title:'There You Are',text:'Elias notices you immediately. “I was wondering when you\'d show up.”',reward:4,memory:'Elias was waiting for you.'},
{id:'mori',times:['morning','day','evening'],icon:'🐈‍⬛',title:'Mori Says Hi',text:'Mori appears first. Elias sighs. “Of course he gets to greet you before I do.”',reward:3,memory:'Mori beat Elias to the greeting.'},
{id:'late',times:['night'],icon:'🌙',title:'Late Again',text:'Elias glances at the time. “You\'re seriously checking in this late?” He makes room beside him anyway.',reward:5,memory:'You showed up late and Elias still made room for you.'},
{id:'hoodie',times:['morning','day','evening'],icon:'🖤',title:'Hoodie Privileges',text:'Elias tosses you his hoodie without explanation. “Don\'t make a thing out of it.”',reward:4,memory:'Elias gave you his hoodie for the day.'},
{id:'close',times:['day','evening','night'],icon:'🫶',title:'Come Here',text:'Elias reaches for your hand. “No reason. Just come here.”',reward:5,memory:'Elias just wanted you close.'}
];
const dateScenes={
sushi:{id:'date.sushi',title:'Sushi Date',image:'sushi.PNG',intro:'The restaurant is warm and quiet. Elias immediately sits beside you instead of across from you.',choices:[
{id:'steal',text:'Steal one of his sushi pieces.',result:'Elias looks at the empty spot on his plate, then at you. “You know you could\'ve just asked.” He gives you another piece anyway.',hearts:3,icon:'🍣',memory:"You stole Elias's sushi and he gave you another piece anyway."},
{id:'shoulder',text:'Rest your head on his shoulder.',result:'He goes still for half a second, then leans his head against yours. “Comfortable?”',hearts:5,icon:'🖤',memory:'You rested against Elias while waiting for dessert.'}]},
movie:{id:'date.movie',title:'Movie Night',image:'movie.PNG',intro:'The movie has barely started and Elias has already taken most of the blanket.',choices:[
{id:'blanket',text:'Steal the blanket back.',result:'Elias looks offended for two seconds before pulling you closer so you both fit.',hearts:4,icon:'🎬',memory:'The blanket fight ended with both of you squeezed underneath it.'},
{id:'sleep',text:'Pretend to fall asleep on him.',result:'He lowers the volume. A few minutes later: “I know you\'re awake, by the way.”',hearts:5,icon:'🍿',memory:'Elias knew you were pretending to sleep but let you stay there.'}]},
walk:{id:'date.walk',title:'Night Walk',image:'walk.PNG',intro:'The streets are quiet and cool. Elias notices your hands are cold.',choices:[
{id:'hand',text:'Reach for his hand.',result:'He threads his fingers through yours immediately. “Yeah. That\'s better.”',hearts:5,icon:'🌙',memory:'You held hands the entire way home.'},
{id:'cold',text:"Tell him you're freezing.",result:'Elias keeps you tucked against his side. “You\'re dramatic.” He doesn\'t let go.',hearts:4,icon:'✨',memory:'Elias called you dramatic while keeping you warm.'}]},
home:{id:'date.home',title:'Stay Home with Mori',image:'home.PNG',intro:'Mori climbs between you and Elias like he personally planned the evening.',choices:[
{id:'mori',text:'Give Mori all your attention.',result:'Mori starts purring. Elias: “Wow. Okay. I see where I rank.”',hearts:3,icon:'🐈‍⬛',memory:'Mori stole all your attention and Elias pretended not to care.'},
{id:'both',text:'Pull Elias closer too.',result:'Mori stays on your lap while Elias leans against you. “Fine. Shared custody.”',hearts:6,icon:'♡',memory:'You ended up cuddling Elias and Mori at the same time.'}]}}
;
const randomScenes=[
{id:'random.mori-spot',title:'Mori Stole My Spot',image:'morii.PNG',intro:'Mori climbs straight into the spot beside you. Elias stops and stares at him.',choices:[{id:'stay',text:'Let Mori stay.',result:'Elias sits on your other side. “Unbelievable.” Mori looks very pleased.',hearts:2,icon:'🐈‍⬛',memory:"Mori stole Elias's spot and looked very proud of himself."},{id:'both',text:'Pull Elias beside you too.',result:'You make room for both. Elias sighs. “Fine. This works.”',hearts:5,icon:'🤍',memory:'You refused to choose between Elias and Mori, so both stayed.'}]},
{id:'random.staring',title:'Caught Staring',image:'couple.PNG',intro:'You catch Elias staring at you. He looks away half a second too late.',choices:[{id:'what',text:'Ask, “What?”',result:'“Nothing.” You keep staring. “…You\'re pretty. Happy?”',hearts:4,icon:'👀',memory:'You caught Elias staring and forced him to admit why.'},{id:'back',text:'Stare back.',result:'Elias breaks first. “Okay, this is getting weird.”',hearts:3,icon:'😭',memory:'A staring contest somehow became a relationship moment.'}]},
{id:'random.phone',title:'Phone Thief',image:'couple.PNG',intro:'Elias steals your phone and immediately opens the camera.',choices:[{id:'grab',text:'Grab it back.',result:'He takes a horribly timed selfie. “Perfect. Album material.”',hearts:3,icon:'📱',memory:'Elias stole your phone and took an absolutely terrible selfie.'},{id:'pose',text:'Pose dramatically.',result:'You commit completely. Elias starts laughing. “Why are you like this?”',hearts:4,icon:'📸',memory:"You turned Elias's phone theft into a dramatic photoshoot."}]},
{id:'random.sleepy',title:'Too Sleepy',image:'home.PNG',intro:'You end up half asleep beside Elias. He notices immediately.',choices:[{id:'sleep',text:'Fall asleep on him.',result:'You wake later and realize Elias barely moved so he wouldn\'t wake you.',hearts:6,icon:'🌙',memory:'You fell asleep on Elias and he stayed still so you could sleep.'},{id:'awake',text:"Insist you're awake.",result:'“Sure.” Five minutes later, you\'re asleep.',hearts:4,icon:'😴',memory:"You insisted you weren't tired and immediately proved yourself wrong."}]}
];
const specialScenes=[
{min:25,scene:{id:'special.stay',title:'Stay Here',image:'couple.PNG',intro:'You\'re about to get up when Elias catches your hand. “Where are you going?”',choices:[{id:'sit',text:'Sit back down.',result:'Elias looks far too satisfied. “Good choice.”',hearts:6,icon:'🤍',memory:'Elias asked you to stay, so you did.'},{id:'missed',text:'Ask if he missed you.',result:'“You were gone for three seconds.” A pause. “…Yes.”',hearts:7,icon:'😭',memory:'Elias admitted he missed you after approximately three seconds.'}]}},
{min:50,scene:{id:'special.favorite',title:'My Favorite Person',image:'couple.PNG',intro:'Elias quietly says, “You know you\'re my favorite person, right?”',choices:[{id:'same',text:"Tell him he's yours too.",result:'His expression softens. “Yeah? Good.”',hearts:8,icon:'💞',memory:"You and Elias admitted you're each other's favorite person."},{id:'tease',text:'Tease him.',result:'“Forget I said anything.” He\'s obviously smiling.',hearts:6,icon:'🫶',memory:'You teased Elias for being sentimental and he failed to hide his smile.'}]}},
{min:100,scene:{id:'special.us',title:'Us',image:'couple.PNG',intro:'Elias smiles slightly. “I really like this. Us, I mean.”',choices:[{id:'lean',text:'Lean into him.',result:'He rests his cheek against your hair. “Yeah. Exactly this.”',hearts:10,icon:'💗',memory:'Elias told you how much he loves your little world together.'},{id:'same',text:'Tell him you do too.',result:'“Good. Because I\'m keeping you.”',hearts:10,icon:'♡',memory:'You chose each other all over again.'}]}}
];
const album=[
{id:'album.us',title:'Us ♡',image:'couple.PNG',caption:'Our little world started here.',unlock:()=>state.hearts>=10,locked:'Reach 10 hearts'},
{id:'album.sushi',title:'Sushi Date',image:'sushi.PNG',caption:"Sushi tastes better when we're sitting way too close.",unlock:()=>hasSource('date.sushi'),locked:'Go on a sushi date'},
{id:'album.movie',title:'Movie Night',image:'movie.PNG',caption:'We definitely watched the entire movie. Definitely.',unlock:()=>hasSource('date.movie'),locked:'Have a movie night'},
{id:'album.walk',title:'Night Walk',image:'walk.PNG',caption:'Cold hands, quiet streets, and you beside me.',unlock:()=>hasSource('date.walk'),locked:'Take a night walk'},
{id:'album.home',title:'Home ♡',image:'home.PNG',caption:'Sometimes staying home together is the best date.',unlock:()=>hasSource('date.home'),locked:'Stay home together'},
{id:'album.mori',title:'Mori',image:'morii.PNG',caption:'Mori owns the relationship. We merely live in it.',unlock:()=>hasSource('mori.pet')||hasSource('date.home')||state.hearts>=25,locked:'Make a memory with Mori'}
];
function currentLevelIndex(h=state.hearts){let i=0;levels.forEach((l,n)=>{if(h>=l.min)i=n});return i}
function hasMemory(id){return state.memories.some(m=>m.id===id)}
function hasSource(source){return state.memories.some(m=>m.source===source)}
function remember({id,icon='♡',text,source='unknown',date=null,repeat=false}){const key=repeat?`${id}:${date||Date.now()}`:id;if(hasMemory(key))return false;state.memories.push({id:key,icon,text,source,at:Date.now(),date});state.memories=state.memories.slice(-500);save();renderMemories();return true}
function queueLevels(oldHearts,newHearts){const a=currentLevelIndex(oldHearts),b=currentLevelIndex(newHearts);for(let i=a+1;i<=b;i++){if(!state.levelQueue.includes(i))state.levelQueue.push(i);remember({id:`level.${i}`,icon:levels[i].icon,text:`Relationship level reached — ${levels[i].name}.`,source:'level'})}}
function addHearts(amount){const old=state.hearts;state.hearts=clamp(state.hearts+Math.max(0,Math.floor(num(amount))),0,1000000);queueLevels(old,state.hearts);save();renderCore();showNextLevel()}
function dayPart(){const h=new Date().getHours();return h<5?'night':h<11?'morning':h<18?'day':h<22?'evening':'night'}
function dailyEvent(){const part=dayPart(),pool=dailyEvents.filter(x=>x.times.includes(part));return pick(pool,`${today()}-${part}`)||dailyEvents[0]}
function effectiveCurrentStreak(){if(!state.daily.last)return 0;if(state.daily.last===today()||state.daily.last===yesterday())return state.daily.current;return 0}
function renderDaily(){const cur=effectiveCurrentStreak(),best=Math.max(state.daily.best,cur),done=state.daily.last===today();$('#streakCount').textContent=cur;$('#currentStreakText').textContent=`${cur} day${cur===1?'':'s'}`;$('#bestStreakText').textContent=`${best} day${best===1?'':'s'}`;$('#settingsStreak').textContent=`${cur} day${cur===1?'':'s'}`;$('#settingsBestStreak').textContent=`Best: ${best} day${best===1?'':'s'}`;$('#todayTitle').textContent=done?"You're Here ♡":'Daily Check-In ♡';$('#todayText').textContent=done?"Today's little moment is already tucked safely into our memories.":'Come say hi and collect today\'s little moment.';$('#dailyCheckInButton').textContent=done?'Checked in today ✓':'Check in for today ♡';$('#dailyCheckInButton').disabled=done}
function checkIn(){if(state.daily.last===today())return;const t=today(),y=yesterday();state.daily.current=state.daily.last===y?state.daily.current+1:1;state.daily.best=Math.max(state.daily.best,state.daily.current);state.daily.last=t;const d=dailyEvent();remember({id:`daily.${t}`,icon:d.icon,text:`${d.title} — ${d.memory}`,source:'daily',date:t,repeat:true});addHearts(d.reward);$('#dailyPopupIcon').textContent=d.icon;$('#dailyPopupTitle').textContent=d.title;$('#dailyPopupText').textContent=d.text;$('#dailyRewardText').textContent=`+${d.reward} hearts`;setDialogue(d.text,false);renderDaily();openModal($('#dailyOverlay'),$('#closeDaily'))}
function renderRelationship(){const i=currentLevelIndex(),l=levels[i],next=levels[i+1];$('#heartCount').textContent=state.hearts;$('#relationshipName').textContent=l.name;$('#relationshipIcon').textContent=l.icon;$('#relationshipDescription').textContent=l.description;$('#settingsRelationshipName').textContent=l.name;$('#settingsHeartCount').textContent=`${state.hearts} hearts`;if(!next){$('#relationshipProgressText').textContent=`${state.hearts} hearts`;$('#nextLevelText').textContent='Maximum level ♡';$('#relationshipProgressFill').style.width='100%';$('#relationshipProgress').setAttribute('aria-valuenow','100');return}const pct=clamp((state.hearts-l.min)/(next.min-l.min)*100,0,100);$('#relationshipProgressText').textContent=`${state.hearts} / ${next.min} hearts`;$('#nextLevelText').textContent=`Next: ${next.name}`;$('#relationshipProgressFill').style.width=`${pct}%`;$('#relationshipProgress').setAttribute('aria-valuenow',String(Math.round(pct)))}
function showNextLevel(){if(!state.levelQueue.length||!$('#levelOverlay').classList.contains('hidden'))return;if(!$('#dailyOverlay').classList.contains('hidden')||!$('#sceneOverlay').classList.contains('hidden'))return;const i=state.levelQueue[0],l=levels[i];$('#levelUpIcon').textContent=l.icon;$('#levelUpName').textContent=l.name;$('#levelUpText').textContent=l.up;openModal($('#levelOverlay'),$('#closeLevelUp'))}
function closeLevel(){state.levelQueue.shift();save();closeModal($('#levelOverlay'));setTimeout(showNextLevel,40)}
let dialogueTimer;
function setDialogue(text,allowBreaks=false){const el=$('#heroDialogue');clearTimeout(dialogueTimer);el.style.opacity='0';dialogueTimer=setTimeout(()=>{if(allowBreaks){el.replaceChildren(...String(text).split('\n').flatMap((x,i)=>i?[document.createElement('br'),document.createTextNode(x)]:[document.createTextNode(x)]))}else el.textContent=text;el.style.opacity='1'},120)}
function rewardFor(scene,choice){const key=`${scene.id}.${choice.id}`;const first=!state.completed[key];state.completed[key]=(state.completed[key]||0)+1;save();return first?choice.hearts:1}
function openScene(scene){$('#sceneImage').src=scene.image;$('#sceneImage').alt=scene.title;$('#sceneTitle').textContent=scene.title;$('#sceneText').textContent=scene.intro;const box=$('#sceneChoices');box.replaceChildren();scene.choices.forEach(choice=>{const b=document.createElement('button');b.type='button';b.className='scene-choice';const key=`${scene.id}.${choice.id}`;const first=!state.completed[key];b.textContent=`${choice.text}  ·  ${first?`+${choice.hearts}`:'+1 replay'} ♡`;b.onclick=()=>choose(scene,choice);box.appendChild(b)});openModal($('#sceneOverlay'),$('#closeScene'))}
function choose(scene,choice){const reward=rewardFor(scene,choice);remember({id:`memory.${scene.id}.${choice.id}`,icon:choice.icon,text:`${scene.title} — ${choice.memory}`,source:scene.id});addHearts(reward);setDialogue(choice.result,false);const box=$('#sceneChoices');box.replaceChildren();const r=document.createElement('div');r.className='scene-result';r.textContent=choice.result;const b=document.createElement('button');b.type='button';b.className='scene-choice';b.textContent=`♡ Continue  +${reward}`;b.onclick=()=>{closeModal($('#sceneOverlay'));setTimeout(showNextLevel,40)};box.append(r,b)}
function randomScene(){const eligible=[...randomScenes,...specialScenes.filter(x=>state.hearts>=x.min).map(x=>x.scene)];let pool=eligible.filter(x=>!state.recentRandom.includes(x.id));if(!pool.length)pool=eligible;const scene=pool[Math.floor(Math.random()*pool.length)];state.recentRandom.push(scene.id);state.recentRandom=state.recentRandom.slice(-3);save();return scene}
function renderMemories(){const list=$('#memoriesList');list.replaceChildren();$('#memoryCount').textContent=`${state.memories.length} unlocked`;if(!state.memories.length){const e=document.createElement('div');e.className='empty';e.textContent='Your memories will appear here ♡';list.appendChild(e);return}state.memories.slice().reverse().forEach(m=>{const item=document.createElement('div');item.className='memory';const ic=document.createElement('div');ic.className='memory-icon';ic.textContent=m.icon;const tx=document.createElement('div');tx.className='memory-text';tx.textContent=m.date?`${m.text} · ${m.date}`:m.text;const h=document.createElement('div');h.className='memory-heart';h.textContent='♡';item.append(ic,tx,h);list.appendChild(item)})}
let albumRendered=false;
function renderAlbum(){const grid=$('#albumGrid');grid.replaceChildren();let unlocked=0;album.forEach(p=>{const ok=p.unlock();if(ok)unlocked++;const b=document.createElement('button');b.type='button';b.className=`album-photo${ok?'':' locked'}`;b.disabled=!ok;const im=document.createElement('img');im.src=p.image;im.alt=ok?p.title:'Locked memory';im.className='album-photo-image';im.loading='lazy';const info=document.createElement('div');info.className='album-photo-info';const strong=document.createElement('strong');strong.textContent=ok?p.title:'Locked Memory';const small=document.createElement('small');small.textContent=ok?'Tap to open ♡':p.locked;info.append(strong,small);b.append(im,info);if(!ok){const lock=document.createElement('div');lock.className='album-lock';const s=document.createElement('span');s.textContent='🔒';const t=document.createElement('small');t.textContent=p.locked;lock.append(s,t);b.appendChild(lock)}else b.onclick=()=>openPhoto(p);grid.appendChild(b)});$('#albumProgress').textContent=`${unlocked} / ${album.length} unlocked`;$('#albumProgressFill').style.width=`${unlocked/album.length*100}%`;albumRendered=true}
function openPhoto(p){$('#photoViewerImage').src=p.image;$('#photoViewerImage').alt=p.title;$('#photoViewerTitle').textContent=p.title;$('#photoViewerCaption').textContent=p.caption;openModal($('#photoOverlay'),$('#closePhoto'))}
let lastFocus=null;
function openModal(el,focus){lastFocus=document.activeElement;el.classList.remove('hidden');document.body.classList.add('modal-open');requestAnimationFrame(()=>focus?.focus())}
function closeModal(el){el.classList.add('hidden');if($$('.scene-overlay:not(.hidden),.level-overlay:not(.hidden),.photo-overlay:not(.hidden),.daily-overlay:not(.hidden)').length===0)document.body.classList.remove('modal-open');lastFocus?.focus?.()}
function closeTopModal(){const open=$$('.photo-overlay:not(.hidden),.daily-overlay:not(.hidden),.level-overlay:not(.hidden),.scene-overlay:not(.hidden)');if(!open.length)return false;const el=open[0];if(el.id==='levelOverlay')closeLevel();else{closeModal(el);setTimeout(showNextLevel,40)}return true}
function petMori(){const options=['Mori purrs immediately. Elias looks offended.','Mori headbutts your hand for more attention.','Mori flops dramatically onto his side.','Mori stares at Elias. Elias: “Don\'t start.”','Mori has decided your lap belongs to him now.'];const d=today();let reward=0;if(state.mori.lastRewardDate!==d){state.mori.lastRewardDate=d;state.mori.rewardCount=0}if(state.mori.rewardCount<3){reward=1;state.mori.rewardCount++}$('#moriText').textContent=options[Math.floor(Math.random()*options.length)]+(reward?'  +1 ♡':'  Mori has collected today\'s tribute.');if(!hasSource('mori.pet'))remember({id:'memory.mori.pet',icon:'🐈‍⬛',text:'You gave Mori the attention he clearly deserved.',source:'mori.pet'});save();if(reward)addHearts(reward)}
function renderCore(){renderRelationship();renderDaily();renderMemories();if(albumRendered||state.page==='album')renderAlbum()}
function showPage(page){state.page=page;save();const actual=page==='memories'?'home':page;$('#homePage').classList.toggle('hidden',actual!=='home');$('#moriPage').classList.toggle('hidden',actual!=='mori');$('#albumPage').classList.toggle('hidden',actual!=='album');$('#settingsPage').classList.toggle('hidden',actual!=='settings');$$('.nav-button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));if(page==='album')renderAlbum();if(page==='settings'){renderRelationship();renderDaily()}if(page==='memories'){requestAnimationFrame(()=>$('.memory-area')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'}))}else window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}
function greeting(){const h=new Date().getHours(),done=state.daily.last===today();let text;if(done)text=h<5?"You're back again? Come here, night owl.":h<12?'Morning again. I already saved today\'s little moment.':h<18?'There you are again. Missed me already?':'Back for the evening? I approve.';else text=h<5?'There you are. Why are we awake this late?':h<10?'Morning. Come stay with me for five more minutes.':h<18?'There you are. What are we doing today?':'There you are. What are we doing tonight?';setDialogue(text,false)}
function reset(){if(!confirm('Reset all hearts, memories, levels and daily streaks?'))return;state=sanitize({version:2,hearts:0,memories:[],daily:{last:'',current:0,best:0},completed:{},mori:{lastRewardDate:'',rewardCount:0},recentRandom:[],page:'home',levelQueue:[]});save();albumRendered=false;renderCore();showPage('home');setDialogue('A fresh start? Okay. Come here.',false)}
function wire(){Object.entries(dateScenes).forEach(([id,s])=>{$(`[data-date="${id}"]`).onclick=()=>openScene(s);const small=$(`[data-date="${id}"] small`);if(small){const vals=s.choices.map(c=>c.hearts);small.textContent=vals.every(v=>v===vals[0])?`💗 +${vals[0]}`:`💗 +${Math.min(...vals)}–${Math.max(...vals)}`}});$('#randomEventButton').onclick=()=>openScene(randomScene());$('#dailyCheckInButton').onclick=checkIn;$('#petMoriButton').onclick=petMori;$('#resetButton').onclick=reset;$$('.nav-button').forEach(b=>b.onclick=()=>showPage(b.dataset.page));$('#closeScene').onclick=()=>{closeModal($('#sceneOverlay'));setTimeout(showNextLevel,40)};$('#closeDaily').onclick=()=>{closeModal($('#dailyOverlay'));setTimeout(showNextLevel,40)};$('#closeLevelUp').onclick=closeLevel;$('#closePhoto').onclick=()=>closeModal($('#photoOverlay'));[$('#sceneOverlay'),$('#photoOverlay')].forEach(el=>el.onclick=e=>{if(e.target===el){closeModal(el);setTimeout(showNextLevel,40)}});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeTopModal()});document.addEventListener('visibilitychange',()=>{if(!document.hidden){renderDaily();greeting()}});window.addEventListener('pageshow',()=>{renderDaily();greeting()});setInterval(()=>{const d=today();if(renderDaily._day!==d){renderDaily._day=d;renderDaily();greeting()}},60000)}
function init(){const rel=$('.relationship-progress');if(rel){rel.id='relationshipProgress';rel.setAttribute('role','progressbar');rel.setAttribute('aria-valuemin','0');rel.setAttribute('aria-valuemax','100')}const ap=$('.album-progress-bar');if(ap){ap.setAttribute('role','progressbar');ap.setAttribute('aria-label','Album completion')};wire();renderCore();showPage(state.page);greeting();save();console.info('Our Little World 2.0 loaded')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();